version = 1

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["angular"]

[[transformers]]
name = "isort"
enabled = true

[[transformers]]
name = "prettier"
enabled = true

[[transformers]]
name = "standardjs"
enabled = true
